# Generated by Django 3.0.6 on 2021-03-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=20, unique=True)),
                ('initialbal', models.IntegerField(default=0)),
                ('accno', models.IntegerField(default=0)),
                ('contactnumber', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=100)),
                ('pernumber', models.IntegerField(default=0)),
                ('operator', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.IntegerField(unique=True)),
                ('otpnumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Userfeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactno', models.IntegerField(default=0)),
                ('complaintdes', models.CharField(max_length=500)),
            ],
        ),
    ]
